//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOIKnjiznicaWebServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Protocol
    {
        public int id { get; set; }
        public string naziv_auth_protokola { get; set; }
    }
}
